name: Allure Report Workflow

on:
  workflow_dispatch:

jobs:
  run_tests_and_generate_report:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Download and Install Allure
      run: |
        # Download Allure CLI binary
        Invoke-WebRequest -Uri "https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.18.1/allure-commandline-2.18.1.zip" -OutFile "allure.zip"
        
        # Extract Allure CLI
        Expand-Archive -Path allure.zip -DestinationPath allure
        
        # Add Allure to PATH
        $env:Path += ";${{ github.workspace }}\\allure\\allure-commandline-2.18.1\\bin"
        
        # Confirm Allure installation
        allure --version

    - name: Run Tests and Generate Allure Report
      run: |
        pytest --alluredir=allure-results
        allure generate allure-results -o allure-report --clean

    - name: Deploy Allure Report to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages
