name: Run Tests and Publish Allure Report

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Use the desired Python version

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests with Allure
      - name: Run tests with pytest and generate Allure results
        run: |
          mkdir -p allure-results
          pytest --alluredir=allure-results

      # Step 5: Generate Allure report
      - name: Generate Allure report
        run: |
          mkdir -p allure-report
          allure generate allure-results -o allure-report --clean
        env:
          ALLURE_HOME: /usr/share/allure # Specify Allure home if necessary

      # Step 6: Deploy Allure report to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
