name: Run Tests and Publish Allure Report

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.4' # Use the desired Python version

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Download and install Allure command-line tool
      - name: Install Allure CLI
        run: |
          ALLURE_VERSION=2.17.3
          wget -q "https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz"
          tar -xzf "allure-${ALLURE_VERSION}.tgz"
          sudo mv "allure-${ALLURE_VERSION}" /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # Step 5: Run tests with Allure
      - name: Run tests with pytest and generate Allure results
        run: |
          mkdir -p allure-results
          pytest --alluredir=allure-results

      # Step 6: Generate Allure report
      - name: Generate Allure report
        run: |
          mkdir -p allure-report
          allure generate allure-results -o allure-report --clean

      # Step 7: Deploy Allure report to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
