name: Hello World Workflow

# Trigger the workflow on any push or pull request to the repository
on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Print "Hello, World!" message
      - name: Print Hello, World!
        run: echo "Hello, World!"
